version: "2"

run:
  timeout: 5m

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - errcheck
    - gocheckcompilerdirectives
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - wastedassign
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
